### ISSUE TITLE
Name field in complaints form

### ISSUE THREAD

**Issue by vigneshmanix** [Rishikc/Hostel-site#12]
Roll number is known after logging in.
So get name from LDAP.
Avoid redundant data.

**Comment by kousiksatish** [comment]
OCTA server is accessible only through the intranet right? What if a person logs in through other networks?? We can't get the name...

**Comment by vigneshmanix** [comment]
The LDAP request is made from our server, not from the client

**Comment by kousiksatish** [comment]
Ok...
