### ISSUE TITLE
Typo in URI

### ISSUE THREAD

**Issue by vigneshmanix** [Rishikc/Hostel-site#17]
Line 19 of resources/views/base.blade.php 

``` html
<link href="{{asset('/font-awesome/css/font-awesome.min.css')}}font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
```

Please fix this

**Comment by sriranganathan** [comment]
Are we even using font-awesome. I found that the font awesome icons are used in three views.

<ol>
<li><b>/resources/views/errors/index.blade.php</b>  which is not used anywhere.</li>
<li><b>/resources/views/vendor/base.blade.php</b> which is again not used.</li>
<li><b>/resources/views/vendor/home.php</b> which is again not used.</li>
</ol>
